name: Check

on: [push, pull_request]

jobs:
  lint:
    name: Lint and build the project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run checks
        run: yarn run check
