name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Lint the codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run eslint
        run: yarn lint
      - name: Build
        run: yarn build
